steps:
  # Step 1: Build the Docker image
  # The image is tagged with the Git short commit SHA ($SHORT_SHA).
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/cloudhub-apptopology-golden/github-source-test/cart-app:${SHORT_SHA}'
      - './cart-app'  # Path to the directory containing the Dockerfile

# Images to push to Artifact Registry.
# Cloud Build automatically pushes images listed here after the steps are done.
images:
  - 'us-central1-docker.pkg.dev/cloudhub-apptopology-golden/github-source-test/cart-app:${SHORT_SHA}'

options:
  requestedVerifyOption: VERIFIED
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
