steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/sdlc-og-test/og-test/app:latest'
      - './app'

# Only upload the image corresponding to the project this is being run from
images:
  - 'us-central1-docker.pkg.dev/sdlc-og-test/og-test/app:latest'

options:
  requestedVerifyOption: VERIFIED
  logging: CLOUD_LOGGING_ONLY
